// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR4zk4WBy-EEMbihxNrVMXmVSKRaBvMrQ',
    appId: '1:860788680711:web:72198348cc47ecd89c62a2',
    messagingSenderId: '860788680711',
    projectId: 'splitmate-mobile',
    authDomain: 'splitmate-mobile.firebaseapp.com',
    storageBucket: 'splitmate-mobile.firebasestorage.app',
    measurementId: 'G-MW51JB5BTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCa-NNPj4rfzpVhovbawPt-t9v8jS-uQI',
    appId: '1:860788680711:android:125fb404d76e78e79c62a2',
    messagingSenderId: '860788680711',
    projectId: 'splitmate-mobile',
    storageBucket: 'splitmate-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZfR4D_1cyedj4BkKezb1i-xesAw3h-_A',
    appId: '1:860788680711:ios:617eca2f02ab513e9c62a2',
    messagingSenderId: '860788680711',
    projectId: 'splitmate-mobile',
    storageBucket: 'splitmate-mobile.firebasestorage.app',
    iosBundleId: 'com.example.splitmateMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZfR4D_1cyedj4BkKezb1i-xesAw3h-_A',
    appId: '1:860788680711:ios:617eca2f02ab513e9c62a2',
    messagingSenderId: '860788680711',
    projectId: 'splitmate-mobile',
    storageBucket: 'splitmate-mobile.firebasestorage.app',
    iosBundleId: 'com.example.splitmateMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR4zk4WBy-EEMbihxNrVMXmVSKRaBvMrQ',
    appId: '1:860788680711:web:80b984bccde3f4ee9c62a2',
    messagingSenderId: '860788680711',
    projectId: 'splitmate-mobile',
    authDomain: 'splitmate-mobile.firebaseapp.com',
    storageBucket: 'splitmate-mobile.firebasestorage.app',
    measurementId: 'G-X8CPLW48YX',
  );
}
